### ISSUE TITLE
在windows环境下安装，报gbk编码异常

### ISSUE THREAD

**Issue by oychao1988** [Daphnis-z/py3fdfs-pypi.org#1]
Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "c:\Users\dyf\AppData\Local Temppip-reg-build-zs3khnyg\setup.py", line 10， in <module>
        long_description = f.read()
UnicodeDecodeError：'gbk' codec can't decode byte @xaf in position 42: illegal multibyte sequence

估计应该是setup.py的第9行，读取readme.md时，中文解析异常的问题

**Comment by waketzheng** [comment]
@oychao1988 能否试一下这个https://github.com/waketzheng/fastdfs-client-python
看看会不会有同样的问题
